// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAf4OtbpsFW8m9EPum2mkviOrxj06j3Q',
    appId: '1:594059965351:web:77413077c1acb277253c82',
    messagingSenderId: '594059965351',
    projectId: 'chaty-77c67',
    authDomain: 'chaty-77c67.firebaseapp.com',
    storageBucket: 'chaty-77c67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2rNKhXWvLQVcKYBtOkrdE2ETvxX2Dyo',
    appId: '1:594059965351:android:860480a23f3e1bf6253c82',
    messagingSenderId: '594059965351',
    projectId: 'chaty-77c67',
    storageBucket: 'chaty-77c67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgukAokB-cJlutt8OOoZTApF-H97VD7cg',
    appId: '1:594059965351:ios:533d7ad0c9183c60253c82',
    messagingSenderId: '594059965351',
    projectId: 'chaty-77c67',
    storageBucket: 'chaty-77c67.appspot.com',
    iosClientId: '594059965351-kgoqarsjda966nibblrcdert6t0fa61e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgukAokB-cJlutt8OOoZTApF-H97VD7cg',
    appId: '1:594059965351:ios:fafadb7c62232a39253c82',
    messagingSenderId: '594059965351',
    projectId: 'chaty-77c67',
    storageBucket: 'chaty-77c67.appspot.com',
    iosClientId: '594059965351-s9mg1f5u4qifh0d33r5ruue7u9m4fo1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaty.RunnerTests',
  );
}
